project:
  seed: 42
  simulate_label: "data/simulate/labels.tsv"
  simulate_vcfs: "data/simulate/truth.vcf.gz"
  simulate_vcf_idx: "data/simulate/truth.vcf.gz.tbi"
  reads : "data/reads"


msprime:
  N_perpop: 100
  ne: 10000
  mu: 2e-8
  rec: 1e-8
  seed: 42
  l: 100000
  model: "hudson"

reads:
  read_len: 150
  err: 0.001
  insert_mean: 350
  insert_sd: 35
  l: 100000      # 可省略，默认用 msprime.l
  depth: 10.0
